/* @pjs preload=
"img/home.png,
img/home1.png,
img/home2.png,
img/home3.png,
img/home4.png,
img/about1.png,
img/about2.png,
img/skill1.png,
img/skill2.png,
img/experience1.png,
img/experience2.png,
img/hope1.png,
img/botton1.png,
img/botton2.png"; */
